---
title: "Workshop Contents"
format: html
html-table-processing: none
jupyter: python3
---

This Great Tables workshop will teach you about what the package can do, and, it'll give you an opportunity to experiment with the API. 

The goal of the workshop is to introduce you to a lot of examples and provide some time to generate some sample tables, learning bit-by-bit as we go.

Each module of the workshop focuses on a different family of methods, with relevant examples and exercises in each. They are all presented here as **Quarto** (.qmd) files with one file for each workshop module:

- `"01-create-table.qmd"`

- `"02-create-modify-parts.qmd"`

- `"02z-PRACTICE-01-02.qmd"`

- `"03-format-data.qmd"`

- `"04-modify-columns.qmd"`

- `"04z-PRACTICE-03-04.qmd"`

- `"05-table_option_methods.qmd"`

- `"05z-PRACTICE-05.qmd"`

You can navigate to any of these and modify the code within the self-contained code chunks. Entire **Quarto** files can be rendered to HTML.

### Installing Great Tables

You can install Great Tables on your system by using pip:

```{bash}
#| eval: False
pip install great_tables
```

